import { db } from "..";
import { colores } from "../schema";

export async function insertarColores() {
  // modificar la ruta de la imagen en el insert
  const newColores = await db.insert(colores).values([
    {
      modelo: "laca",
      nombreColor: "Blanco",
      imagenColor: "Blanco.png",
    },
    {
      modelo: "laca",
      nombreColor: "Aluminio",
      imagenColor: "Aluminio.png",
    },
    {
      modelo: "laca",
      nombreColor: "Steel",
      imagenColor: "Steel.png",
    },
    {
      modelo: "laca",
      nombreColor: "Gris Oscuro",
      imagenColor: "GrisOscuro.png",
    },
    {
      modelo: "laca",
      nombreColor: "Negro",
      imagenColor: "Negro.png",
    },
    {
      modelo: "laca",
      nombreColor: "Chocolate",
      imagenColor: "Chocolate.png",
    },
    {
      modelo: "laca",
      nombreColor: "Granate",
      imagenColor: "Granate.png",
    },
    {
      modelo: "laca",
      nombreColor: "Rojo",
      imagenColor: "Rojo.png",
    },
    {
      modelo: "laca",
      nombreColor: "Naranja",
      imagenColor: "Naranja.png",
    },
    {
      modelo: "laca",
      nombreColor: "Moca",
      imagenColor: "Moca.png",
    },
    {
      modelo: "laca",
      nombreColor: "Crema",
      imagenColor: "Crema.png",
    },
    {
      modelo: "laca",
      nombreColor: "Azul Cielo",
      imagenColor: "AzulCielo.png",
    },
    {
      modelo: "laca",
      nombreColor: "Turquesa",
      imagenColor: "Turquesa.png",
    },
    {
      modelo: "laca",
      nombreColor: "Hielo",
      imagenColor: "Hielo.png",
    },
    {
      modelo: "laca",
      nombreColor: "Verde Manzana",
      imagenColor: "VerdeManzana.png",
    },
    {
      modelo: "laca",
      nombreColor: "Verde Kiwi",
      imagenColor: "VerdeKiwi.png",
    },

    //Cambio de modelo
    {
      modelo: "barniz",
      nombreColor: "Wengue",
      imagenColor: "Wengue.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Rural",
      imagenColor: "Rural.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Aurora",
      imagenColor: "Aurora.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Nogal",
      imagenColor: "Nogal.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Cerezo Oscuro",
      imagenColor: "CerezoOscuro.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Cerezo Claro",
      imagenColor: "CerezoClaro.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Haya Miel",
      imagenColor: "HayaMiel.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Haya Natural",
      imagenColor: "HayaNatural.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Haya Lavada",
      imagenColor: "HayaLavada.png",
    },
    {
      modelo: "barniz",
      nombreColor: "Ceniza",
      imagenColor: "Ceniza.png",
    },

    //Cambio de modelo
    {
      modelo: "cristal 3mm",
      nombreColor: "Polar",
      imagenColor: "Polar.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Gris Claro",
      imagenColor: "GrisClaro.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Gris Medio",
      imagenColor: "GrisMedio.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Gris Oscuro",
      imagenColor: "GrisOscuro.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Negro",
      imagenColor: "Negro.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Chocolate",
      imagenColor: "Chocolate.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Granate",
      imagenColor: "Granate.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Rojo",
      imagenColor: "Rojo.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Naranja",
      imagenColor: "Naranja.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Moca",
      imagenColor: "Moca.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Crema",
      imagenColor: "Crema.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Azul Cielo",
      imagenColor: "AzulCielo.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Turquesa",
      imagenColor: "Turquesa.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Hielo",
      imagenColor: "Hielo.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Verde Manzana",
      imagenColor: "VerdeManzana.png",
    },
    {
      modelo: "cristal 3mm",
      nombreColor: "Verde Kiwi",
      imagenColor: "VerdeKiwi.png",
    },

    //Cambio de modelo
    {
      modelo: "cristal 8mm",
      nombreColor: "Polar",
      imagenColor: "Polar.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Gris Oscuro",
      imagenColor: "GrisOscuro.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Negro",
      imagenColor: "Negro.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Chocolate",
      imagenColor: "Chocolate.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Berenjena",
      imagenColor: "Berenjena.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Azul Cielo",
      imagenColor: "AzulCielo.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Turquesa",
      imagenColor: "Turquesa.png",
    },
    {
      modelo: "cristal 8mm",
      nombreColor: "Hielo",
      imagenColor: "Hielo.png",
    },

    //Cambio de modelo
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Nieve",
      imagenColor: "Nieve.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Gris Claro",
      imagenColor: "GrisClaro.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Gris Medio",
      imagenColor: "GrisMedio.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Verde Manzana",
      imagenColor: "VerdeManzana.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Verde Kiwi",
      imagenColor: "VerdeKiwi.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Granate",
      imagenColor: "Granate.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Rojo",
      imagenColor: "Rojo.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Naranja",
      imagenColor: "Naranja.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Moca",
      imagenColor: "Moca.png",
    },
    {
      modelo: "cristal 8mm extraclaro",
      nombreColor: "Crema",
      imagenColor: "Crema.png",
    },

    //Cambio de modelo
    {
      modelo: "laminado",
      nombreColor: "Blanco",
      imagenColor: "Blanco.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Gris Claro F7927",
      imagenColor: "GrisClaro.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Gris Medio F7961",
      imagenColor: "GrisMedio.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Gris oscuro F7912",
      imagenColor: "GrisOscuro.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Negro",
      imagenColor: "Negro.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Aluminio",
      imagenColor: "Aluminio.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Blush",
      imagenColor: "Blush.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Sol",
      imagenColor: "Sol.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Crema F7932",
      imagenColor: "Crema.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Moca F7929",
      imagenColor: "Moca.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Eart F5342",
      imagenColor: "Eart.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Chocolate F2200",
      imagenColor: "Chocolate.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Granate F7966",
      imagenColor: "Granate.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Rojo",
      imagenColor: "Rojo.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Naranja F2962",
      imagenColor: "Naranja.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Just Blue",
      imagenColor: "JustBlue.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Azul Cielo F7851",
      imagenColor: "AzulCielo.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Turquesa F5347",
      imagenColor: "Turquesa.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "V.Manzana F6901",
      imagenColor: "VerdeManzana.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "V.Kiwi F8755",
      imagenColor: "VerdeKiwi.png",
      acabado: "Brillo, Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Nogal Canaletto",
      imagenColor: "NogalCanaletto.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Vivid Cherry K7021",
      imagenColor: "VividCherry.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Vosges Pear F2884",
      imagenColor: "VosgesPear.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Alder F0192",
      imagenColor: "Alder.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Sand Maple F2731",
      imagenColor: "SandMaple.png",
      acabado: "Mate",
    },
    {
      modelo: "laminado",
      nombreColor: "Oxidised Beamwood",
      imagenColor: "OxidisedBeamwood.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Roble Aurora",
      imagenColor: "RobleAurora.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Fresno Taiga",
      imagenColor: "FresnoTaiga.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Ceniza Blanca F8841",
      imagenColor: "CenizaBlanca.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Roble Rural F8853",
      imagenColor: "RobleRural.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Roble Nevada F8588",
      imagenColor: "RobleNevada.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Cemento Blanco",
      imagenColor: "CementoBlanco.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Cemento Gris",
      imagenColor: "CementoGris.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Yin Marble",
      imagenColor: "YinMarble.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Marmol Hades",
      imagenColor: "MarmolHades.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Stone Rock",
      imagenColor: "StoneRock.png",
      acabado: "Natural",
    },
    {
      modelo: "laminado",
      nombreColor: "Cerezo Eco",
      imagenColor: "CerezoEco.png",
      acabado: "Mate",
    },

    //Cambio de modelo
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Blanco",
      imagenColor: "TexBlanco.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Negro",
      imagenColor: "TexNegro.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Plata",
      imagenColor: "TexPlata.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Azul Cielo",
      imagenColor: "TexAzulCielo.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Azul Marino",
      imagenColor: "TexAzulMarino.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Antracita",
      imagenColor: "TexAntracita.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Rojo",
      imagenColor: "TexRojo.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Cobre",
      imagenColor: "TexCobre.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Chocolate",
      imagenColor: "TexChocolate.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex Moca",
      imagenColor: "TexMoca.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Tex fucsia",
      imagenColor: "TexFucsia.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Ivory",
      imagenColor: "Ivory.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Blanco",
      imagenColor: "GeminiBlanco.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Negro",
      imagenColor: "GeminiNegro.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Gris",
      imagenColor: "GeminiGris.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Stone",
      imagenColor: "GeminiStone.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Chocolate",
      imagenColor: "GeminiChocolate.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Rojo",
      imagenColor: "GeminiRojo.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Marsala",
      imagenColor: "GeminiMarsala.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Power Rose",
      imagenColor: "GeminiPowerRose.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Blue Fog",
      imagenColor: "GeminiBlueFog.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Gemini Light Stone",
      imagenColor: "GeminiLightStone.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Urban Granate",
      imagenColor: "UrbanGranate.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Urban Turquesa",
      imagenColor: "UrbanTurquesa.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Blanco",
      imagenColor: "MichiganBlanco.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Gris Medio",
      imagenColor: "MichiganGrisMedio.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Gris Oscuro",
      imagenColor: "MichiganGrisOscuro.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Negro",
      imagenColor: "MichiganNegro.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Arena",
      imagenColor: "MichiganArena.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Chocolate",
      imagenColor: "MichiganChocolate.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Rojo",
      imagenColor: "MichiganRojo.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Naranja",
      imagenColor: "MichiganNaranja.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Melocoton",
      imagenColor: "MichiganMelocoton.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Azul Marino",
      imagenColor: "MichiganAzulMarino.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Michigan Verde Kiwi",
      imagenColor: "MichiganVerdeKiwi.png",
    },
    {
      modelo: "tapizado nvA",
      nombreColor: "Verde Manzana",
      imagenColor: "VerdeManzana.png",
    },

    //Cambio de modelo
    {
      modelo: "tapizado nvC",
      nombreColor: "Blanco",
      imagenColor: "Blanco.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Negro",
      imagenColor: "Negro.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Gris Oscuro",
      imagenColor: "GrisOscuro.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Crema",
      imagenColor: "Crema.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Eart",
      imagenColor: "Eart.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Azul Marino",
      imagenColor: "AzulMarino.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Chocolate",
      imagenColor: "Chocolate.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Rojo",
      imagenColor: "Rojo.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Naranja",
      imagenColor: "Naranja.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Plata",
      imagenColor: "Plata.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Rosa",
      imagenColor: "Rosa.png",
    },
    {
      modelo: "tapizado nvC",
      nombreColor: "Verde Apple",
      imagenColor: "VerdeApple.png",
    },

    //Cambio de modelo
    {
      modelo: "silestone g1",
      nombreColor: "Iconic White",
      imagenColor: "IconicWhite.png",
      grupo: "g5",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Zeus",
      imagenColor: "BlancoZeus.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Miami Vena",
      imagenColor: "MiamiVena.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Nolita",
      imagenColor: "Nolita.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Miami White 17",
      imagenColor: "MiamiWhite.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Snowy Ibiza",
      imagenColor: "SnowyIbiza.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Ariel",
      imagenColor: "Ariel.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Et.Calacatta Gold",
      imagenColor: "EtCalacattaGold.png",
      grupo: "g6",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Et.Statuario",
      imagenColor: "EtStatuario.png",
      grupo: "g5",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Pearl Jasmine",
      imagenColor: "PearlJasmine.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Desert Silver",
      imagenColor: "DesertSilver.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Orion",
      imagenColor: "BlancoOrion.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "WhiteStorm",
      imagenColor: "WhiteStorm.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Yukon",
      imagenColor: "Yukon.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Maple 14",
      imagenColor: "BlancoMaple.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Norte 14",
      imagenColor: "BlancoNorte.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "White Arabesque",
      imagenColor: "WhiteArabesque.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Stellar 13",
      imagenColor: "BlancoStellar.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Bianco River",
      imagenColor: "BiancoRiver.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Lagoon",
      imagenColor: "Lagoon.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Poblenou",
      imagenColor: "Poblenou.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Lyn",
      imagenColor: "Lyn.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Pulsar",
      imagenColor: "Pulsar.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Silken Pearl",
      imagenColor: "SilkenPearl.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Et.Marfil",
      imagenColor: "EtMarfil.png",
      grupo: "g5",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco City",
      imagenColor: "BlancoCity.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Royal Reef",
      imagenColor: "RoyalReef.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Blanco Capri",
      imagenColor: "BlancoCapri.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Tigris Sand",
      imagenColor: "TigrisSand.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Niebla",
      imagenColor: "Niebla.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Et.Serena",
      imagenColor: "EtSerena.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Aluminio Nube",
      imagenColor: "AluminioNube.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Kensho",
      imagenColor: "Kensho.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Camdenb",
      imagenColor: "Camdenb.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Rougui",
      imagenColor: "Rougui.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Seaport",
      imagenColor: "Seaport.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Coral Clay Colour",
      imagenColor: "CoralClayColour.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Noka",
      imagenColor: "Noka.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Unsui",
      imagenColor: "Unsui.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Ironbark",
      imagenColor: "Ironbark.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Calypso",
      imagenColor: "Calypso.png",
      grupo: "g5",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Cygnus 15",
      imagenColor: "Cygnus.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Gris Expo",
      imagenColor: "GrisExpo.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Cemento Spa",
      imagenColor: "CementoSpa.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Marengo",
      imagenColor: "Marengo.png",
      grupo: "g1",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Arden Blue",
      imagenColor: "ArdenBlue.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Merope",
      imagenColor: "Merope.png",
      grupo: "g3",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Negro Stellar",
      imagenColor: "NegroStellar.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Negro Tebas 18",
      imagenColor: "NegroTebas.png",
      grupo: "g2",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Charcoal Soapstone",
      imagenColor: "CharcoalSoapstone.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Corktown",
      imagenColor: "Corktown.png",
      grupo: "g4",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Et.Marquina",
      imagenColor: "EtMarquina.png",
      grupo: "g5",
    },
    {
      modelo: "silestone g1",
      nombreColor: "EtNoir",
      imagenColor: "EtNoir.png",
      grupo: "g6",
    },
    {
      modelo: "silestone g1",
      nombreColor: "Iconic Black",
      imagenColor: "IconicBlack.png",
      grupo: "g4",
    },

    //Cambio de modelo
    {
      modelo: "dekton g1",
      nombreColor: "Uyuni",
      imagenColor: "Uyuni.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Nayla",
      imagenColor: "Nayla.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Zenith",
      imagenColor: "Zenith.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Moone",
      imagenColor: "Moone.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Kairos",
      imagenColor: "Kairos.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Opera",
      imagenColor: "Opera.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Rem",
      imagenColor: "Rem.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Entzo",
      imagenColor: "Entzo.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Aura 15",
      imagenColor: "Aura.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Nilium",
      imagenColor: "Nilium.png",
      grupo: "g2",
    },
    // {
    //   modelo: "dekton g1",
    //   nombreColor: "Blanc Concrete",
    //   imagenColor: "BlacnConcrete.png",
    //   grupo: "g0",
    // },
    {
      modelo: "dekton g1",
      nombreColor: "Makai",
      imagenColor: "Makai.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Lunar",
      imagenColor: "Lunar.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Edora",
      imagenColor: "Edora.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Sasea",
      imagenColor: "Sasea.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Valterra",
      imagenColor: "Valterra.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Kovik",
      imagenColor: "Kovik.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Galema",
      imagenColor: "Galema.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Portum",
      imagenColor: "Portum.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Kreta",
      imagenColor: "Kreta.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Soke",
      imagenColor: "Soke.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Vera",
      imagenColor: "Vera.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Orix",
      imagenColor: "Orix.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Kira",
      imagenColor: "Kira.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Trilium 17",
      imagenColor: "Trilium.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Keranium",
      imagenColor: "Keranium.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Radium",
      imagenColor: "Radium.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Bromo",
      imagenColor: "Bromo.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Laos",
      imagenColor: "Laos.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Fossil",
      imagenColor: "Fossil.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Feroe",
      imagenColor: "Feroe.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Baltic",
      imagenColor: "Baltic.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Eter",
      imagenColor: "Eter.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Laurent",
      imagenColor: "Laurent.png",
      grupo: "g3",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Kelya",
      imagenColor: "Kelya.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Sirius",
      imagenColor: "Sirius.png",
      grupo: "g1",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Domoos",
      imagenColor: "Domoos.png",
      grupo: "g2",
    },
    {
      modelo: "dekton g1",
      nombreColor: "Halo",
      imagenColor: "Halo.png",
      grupo: "g4",
    },
    {
        modelo: "dekton g1",
        nombreColor: "Tundra 19",
        imagenColor: "Tundra.png",
        grupo: "g3",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Vienna",
        imagenColor: "Vienna.png",
        grupo: "g2",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Olimpo",
        imagenColor: "Olimpo.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Natura 18",
        imagenColor: "Natura.png",
        grupo: "g3",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Helena",
        imagenColor: "Helena.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Bergen",
        imagenColor: "Bergen.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Khalo",
        imagenColor: "Khalo.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Arga",
        imagenColor: "Arga.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Taga",
        imagenColor: "Taga.png",
        grupo: "g4",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Korso",
        imagenColor: "Korso.png",
        grupo: "g3",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Sogne",
        imagenColor: "Sogne.png",
        grupo: "g3",
      },
      {
        modelo: "dekton g1",
        nombreColor: "Spectra",
        imagenColor: "Spectra.png",
        grupo: "g4",
      },
  ]);
}
export async function insertarColoresECO() {
  // modificar la ruta de la imagen en el insert
  const newColores = await db.insert(colores).values([
    {
      modelo: "laminado ECO",
      nombreColor: "Blanco ECO",
      imagenColor: "BlancoECO.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Cemento Blanco",
      imagenColor: "CementoBlanco.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Cemento Gris",
      imagenColor: "CementoGris.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Fresno Taiga",
      imagenColor: "FresnoTaiga.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Marmol Hades",
      imagenColor: "MarmolHades.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Nogal Canaletto",
      imagenColor: "NogCanaletto.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Roble Aurora",
      imagenColor: "RobleAurora.png",
    },
    {
      modelo: "laminado ECO",
      nombreColor: "Yin Marble",
      imagenColor: "YinMarble.png",
    },
  ]);
}

