import { db } from "..";
import { mesas } from "../schema";

export async function insertarMesas() {
  // modificar la ruta de la imagen en el insert
  const newMesa = await db.insert(mesas).values([
    {
      modelo: "LOMMA",
      imagen: "lomma.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "100x50, 100x60, 110x70, 120x80, 150x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      tendencia: true,
      precio: "508",
    },
    {
      modelo: "DUBLIN",
      imagen: "m1.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "100x30",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      precio: "508",
    },
    {
      modelo: "TARRAGONA",
      imagen: "ejemplo.png",
      tipoBase: "peninsula",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "ROMA",
      imagen: "m2.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "CADIZ",
      imagen: "m3.png",
      tipoBase: "4 patas",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "SEVILLA",
      imagen: "m4.png",
      tipoBase: "alas",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "ONTARO",
      imagen: "m5.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "DUBLIN",
      imagen: "m6.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: "508",
    },
    {
      modelo: "FRANCIA",
      imagen: "m7.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: "508",
    },
    {
      modelo: "TAILANDIA",
      imagen: "m8.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: "508",
    },
    {
      modelo: "TOKIO",
      imagen: "m9.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "NUEVA YORK",
      imagen: "m10.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: "508",
    },
    {
      modelo: "ESTAMBUL",
      imagen: "m11.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: "508",
    },
    {
      modelo: "LAGOS",
      imagen: "m12.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
    {
      modelo: "SEÚL",
      imagen: "m13.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: "508",
    },
    {
      modelo: "EL CAIRO",
      imagen: "m14.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: "508",
    },
  ]);
}
