import { db } from "..";
import { sillas } from "../schema";

export async function insertarSillas() {
  // modificar la ruta de la imagen en el insert
  const newSillas = await db.insert(sillas).values([
    //INSERT SILLA 1
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      nuevo: true,
      precio: "150, 163, 146",
    },
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Silla alta",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      precio: "162, 175, 175",
    },
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      precio: "174, 200, 200",
    },
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      precio: "163, 186, 186",
    },
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      precio: "153, 177, 177",
    },
    {
      modelo: "SOKE",
      imagen: "soke.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco, negro",
      precio: "146, 159, 159",
    },

    //INSERT SILLA 2
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "150', 163, 163",
    },
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Silla alta",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "162, 175, 175",
    },
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "174, 200, 200",
    },
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "163, 186, 186",
    },
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "153, 177, 177",
    },
    {
      modelo: "PAOLA",
      imagen: "paola.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio, blanco",
      precio: "146, 159, 159",
    },

    //   INSERT SILLA 3
    {
      modelo: "KRITI",
      imagen: "kriti.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "87, 93, 93, 111, 111",
    },
    {
      modelo: "KRITI",
      imagen: "kriti.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "90, 93, 93, 109, 109",
    },
    {
      modelo: "KRITI",
      imagen: "kriti.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      tendencia: true,
      precio: "81, 85, 85, 100, 100",
    },
    {
      modelo: "KRITI",
      imagen: "kriti.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "52, 55, 55, 66, 66",
    },

    //   INSERT SILLA 4
    {
      modelo: "WIND",
      imagen: "wind.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "87, 93, 93, 111, 111",
    },
    {
      modelo: "WIND",
      imagen: "wind.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "90, 93, 93, 109, 109",
    },
    {
      modelo: "WIND",
      imagen: "wind.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      tendencia: true,
      precio: "81, 85, 85, 100, 100",
    },
    {
      modelo: "WIND",
      imagen: "wind.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "52, 55, 55, 66, 66",
    },

    //   INSERT SILLA 5
    {
      modelo: "BEAT",
      imagen: "beat.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "138, 162",
    },
    {
      modelo: "BEAT",
      imagen: "beat.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "174, 197",
    },

    //   INSERT SILLA 6
    {
      modelo: "SOUL",
      imagen: "soul.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "125, 141",
    },
    {
      modelo: "SOUL",
      imagen: "soul.png",
      formato: "Tabuerete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "122, 138",
    },
    {
      modelo: "SOUL",
      imagen: "soul.png",
      formato: "Tabuerete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "115, 118",
    },
    {
      modelo: "SOUL",
      imagen: "soul.png",
      formato: "Tabuerete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "aluminio",
      precio: "104, 119",
    },

    //   INSERT SILLA 7
    {
      modelo: "DUO",
      imagen: "duo.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "81, 87, 87, 99, 99",
    },
    {
      modelo: "DUO",
      imagen: "duo.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "52, 56, 56, 66, 66",
    },

    //   INSERT SILLA 8
    {
      modelo: "OPEN",
      imagen: "open.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "aluminio",
      tendencia: true,
      precio: "128, 143, 156, 156",
    },

    //   INSERT SILLA 9
    {
      modelo: "CASUAL",
      imagen: "casual.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "aluminio",
      nuevo: true,
      precio: "144, 158, 154, 154",
    },

    //   INSERT SILLA 10
    {
      modelo: "HALL",
      imagen: "hall.png",
      formato: "Tabuerete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      tendencia: true,
      precio: "150, 156, 167, 167, 167",
    },
    {
      modelo: "HALL",
      imagen: "hall.png",
      formato: "Tabuerete barra sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "132, 139, 155, 155, 155",
    },
    {
      modelo: "HALL",
      imagen: "hall.png",
      formato: "Tabuerete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "149, 156, 167, 167, 167",
    },
    {
      modelo: "HALL",
      imagen: "hall.png",
      formato: "Tabuerete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "124, 131, 142, 142, 142",
    },
    {
      modelo: "HALL",
      imagen: "hall.png",
      formato: "Tabuerete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco, negro",
      precio: "112, 119, 135, 135, 135",
    },

    //   INSERT SILLA 11
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      tendencia: true,
      precio: "102, 108, 108, 127, 127",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "156, 168, 168, 205, 205",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Tabuerete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "120, 124, 124, 135, 135",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Tabuerete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "89, 92, 92, 116, 116",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Tabuerete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "86, 89, 89, 100, 100",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Tabuerete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "81, 85, 85, 108, 108",
    },
    {
      modelo: "PAROLE",
      imagen: "parole.png",
      formato: "Tabuerete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "53, 56, 56, 77, 77",
    },

    //   INSERT SILLA 12
    {
      modelo: "FOREST",
      imagen: "forest.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "99, 105, 105, 118, 118",
    },
    {
      modelo: "FOREST",
      imagen: "forest.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "171, 186, 186, 212, 212",
    },
    {
      modelo: "FOREST",
      imagen: "forest.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "88, 94, 94, 100, 100",
    },
    {
      modelo: "FOREST",
      imagen: "forest.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "55, 59, 59, 71, 71",
    },

    //   INSERT SILLA 13
    {
      modelo: "LEMON",
      imagen: "lemon.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "96, 88, 101, 114, 114",
    },
    {
      modelo: "LEMON",
      imagen: "lemon.png",
      formato: "Taburete sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "55, 59, 59, 71, 71",
    },

    //   INSERT SILLA 14
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "139, 150, 150, 160, 160",
      nuevo: true,
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "207, 228, 228, 238, 238",
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "134, 145, 145, 155, 155",
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "136, 153, 153, 163, 163",
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Taburete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "86, 89, 89, 99, 99",
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "116, 127, 127, 137, 137",
    },
    {
      modelo: "BARI",
      imagen: "bari.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "53, 56, 56, 66, 66",
    },

    //   INSERT SILLA 15
    {
      modelo: "STAPEL",
      imagen: "stapel.png",
      formato: "Silla apilable",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "aluminio",
      precio: "82, 88, 98",
      tendencia: true,
    },

    //   INSERT SILLA 16
    {
      modelo: "ALOHA",
      imagen: "aloha.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "85, 91, 91, 99, 99",
      nuevo: true,
    },
    {
      modelo: "ALOHA",
      imagen: "aloha.png",
      formato: "Combi",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "153, 168, 168, 188, 188",
    },
    {
      modelo: "ALOHA",
      imagen: "aloha.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "105, 109, 109, 120, 120",
    },
    {
      modelo: "ALOHA",
      imagen: "aloha.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "74, 78, 78, 89, 89",
    },
    {
      modelo: "ALOHA",
      imagen: "aloha.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "55, 59, 59, 71, 71",
    },

    //   INSERT SILLA 17
    {
      modelo: "STYLO",
      imagen: "stylo.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "82, 88, 88, 96, 96",
    },
    {
      modelo: "STYLO",
      imagen: "stylo.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "72, 77, 77, 87, 87",
    },
    {
      modelo: "STYLO",
      imagen: "stylo.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "52, 56, 56, 66, 66",
    },

    //   INSERT SILLA 18
    {
      modelo: "TREBOL",
      imagen: "trebol.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "85, 91, 91, 99, 99",
    },
    {
      modelo: "TREBOL",
      imagen: "trebol.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "111, 114, 114, 122, 122",
    },
    {
      modelo: "TREBOL",
      imagen: "trebol.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "105, 109, 109, 125, 125",
    },
    {
      modelo: "TREBOL",
      imagen: "trebol.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "78, 83, 83, 90, 90",
    },
    {
      modelo: "TREBOL",
      imagen: "trebol.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio",
      precio: "52, 56, 56, 66, 66",
    },

    //   INSERT SILLA 19
    {
      modelo: "ONDA",
      imagen: "onda.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "73, 79, 79, 99, 99",
      tendencia: true,
    },
    {
      modelo: "ONDA",
      imagen: "onda.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "70, 75, 75, 85, 85",
    },
    {
      modelo: "ONDA",
      imagen: "onda.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "52, 56, 56, 66, 66",
    },

    //   INSERT SILLA 20
    {
      modelo: "KER",
      imagen: "ker.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "84, 90, 90, 98, 98",
    },
    {
      modelo: "KER",
      imagen: "ker.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "79, 84, 84, 94, 94",
    },
    {
      modelo: "KER",
      imagen: "ker.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "52, 56, 56, 66, 66",
    },

    //   INSERT SILLA 21
    {
      modelo: "NIJAR",
      imagen: "nijar.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "82, 87, 87, 95, 95",
    },
    {
      modelo: "NIJAR",
      imagen: "nijar.png",
      formato: "Taburete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "65, 69, 69, 81, 81",
    },
    {
      modelo: "NIJAR",
      imagen: "nijar.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "59, 62, 62, 74, 74",
    },

    //   INSERT SILLA 22
    {
      modelo: "SORIA",
      imagen: "soria.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      nuevo: true,
      precio: "83, 89, 89, 101, 101",
    },
    {
      modelo: "SORIA",
      imagen: "soria.png",
      formato: "Taburete bajo con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "72, 76, 76, 84, 84",
    },
    {
      modelo: "SORIA",
      imagen: "soria.png",
      formato: "Taburete bajo sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laminado, laca, barniz",
      colorBastidor: "aluminio, blanco",
      precio: "52, 56, 56, 74, 74",
    },

    //   INSERT SILLA 23
    {
      modelo: "SHELL",
      imagen: "shell.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      nuevo: true,
      tendencia: true,
      precio: "207, 217, 217, 217",
    },

    //   INSERT SILLA 24
    {
      modelo: "FORMA",
      imagen: "forma.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      tendencia: true,
      precio: "232, 244, 244, 244",
    },
    {
      modelo: "FORMA",
      imagen: "forma.png",
      formato: "Taburete barra sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "154, 158, 158, 158",
    },
    {
      modelo: "FORMA",
      imagen: "forma.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "232, 244, 244, 244",
    },
    {
      modelo: "FORMA",
      imagen: "forma.png",
      formato: "Taburete alto sin respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "154, 158, 158, 158",
    },

    //   INSERT SILLA 25
    {
      modelo: "CAPRI",
      imagen: "capri.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      tendencia: true,
      precio: "180, 185, 185, 185",
    },

    // INSERT SILLA 26
    {
      modelo: "ELEGANCE",
      imagen: "elegance.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "179, 184, 193, 193",
    },
    {
      modelo: "ELEGANCE",
      imagen: "elegance.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "177, 182, 191, 191",
    },

    // INSERT SILLA 27
    {
      modelo: "NINE",
      imagen: "nine.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "madera haya maciza",
      nuevo: true,
      tendencia: true,
      precio: "163, 173",
    },
    {
      modelo: "NINE",
      imagen: "nine.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "madera haya maciza",
      precio: "200, 210",
    },
    {
      modelo: "NINE",
      imagen: "nine.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "madera haya maciza",
      precio: "200, 210",
    },

    // INSERT SILLA 28
    {
      modelo: "INDIE",
      imagen: "indie.png",
      formato: "Silla",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      nuevo: true,
      precio: "204, 209, 210, 210",
    },
    {
      modelo: "INDIE",
      imagen: "indie.png",
      formato: "Taburete barra con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "203, 207, 208, 208",
    },
    {
      modelo: "INDIE",
      imagen: "indie.png",
      formato: "Taburete alto con respaldo",
      materialAsiento: "tapizado nvC, tapizado nvA, laca, barniz",
      colorBastidor: "madera haya maciza",
      precio: "203, 207, 208, 208",
    },

    // INSERT SILLA 29
    {
      modelo: "SHARA",
      imagen: "shara.png",
      formato: "Taburete",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "Estandar cromo",
      nuevo: true,
      precio: "155, 160, 149",
    },

    // INSERT SILLA 30
    {
      modelo: "LORA",
      imagen: "lora.png",
      formato: "Taburete",
      materialAsiento: "tapizado nvC, tapizado nvA, laca",
      colorBastidor: "Estandar cromo",
      tendencia: true,
      precio: "155, 160, 149",
    },

    // INSERT SILLA 30
    {
      modelo: "BOLERA",
      imagen: "bolera.png",
      formato: "Taburete",
      materialAsiento: "tapizado nvC, tapizado nvA",
      colorBastidor: "Estandar cromo",
      tendencia: true,
      nuevo: true,
      precio: "118, 135",
    },
  ]);
}
