import { db } from "..";
import { bancos } from "../schema";

export async function insertarBancos() {
  // modificar la ruta de la imagen en el insert
  const newBancos = await db.insert(bancos).values([
    //Modelo TRAVEL
    {
      modelo: "TRAVEL",
      imagen: "banco1.png",
      modulo: "45",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "376, 395",
    },
    {
      modelo: "TRAVEL",
      imagen: "banco1.png",
      modulo: "90",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "499, 524",
    },
    {
      modelo: "TRAVEL",
      imagen: "banco1.png",
      modulo: "120",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "583, 612",
    },
    {
      modelo: "TRAVEL",
      imagen: "banco1.png",
      modulo: "150",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "638, 669",
    },
    {
      modelo: "TRAVEL",
      imagen: "banco1.png",
      modulo: "45Rincon",
      materialBastidor: "laminado",
      zocalo: true,
      precio: "416, 437",
    },
    //Modelo TRAPEZZE
    {
      modelo: "TRAPEZZE",
      imagen: "banco2.png",
      modulo: "45",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 93,
      zocalo: true,
      precio: "250, 262",
    },
    {
      modelo: "TRAPEZZE",
      imagen: "banco2.png",
      modulo: "90",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 121,
      zocalo: true,
      precio: "330, 346",
    },
    {
      modelo: "TRAPEZZE",
      imagen: "banco2.png",
      modulo: "120",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 139,
      zocalo: true,
      precio: "397, 417",
    },
    {
      modelo: "TRAPEZZE",
      imagen: "banco2.png",
      modulo: "150",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 156,
      zocalo: true,
      precio: "438, 460",
    },
    {
      modelo: "TRAPEZZE",
      imagen: "banco2.png",
      modulo: "45Rincon",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 93,
      zocalo: true,
      precio: "297, 312",
    },
    //Modelo SCALA
    {
      modelo: "SCALA",
      imagen: "banco3.png",
      modulo: "45",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "376, 395",
    },
    {
      modelo: "SCALA",
      imagen: "banco3.png",
      modulo: "90",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "499, 524",
    },
    {
      modelo: "SCALA",
      imagen: "banco3.png",
      modulo: "120",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "583, 612",
    },
    {
      modelo: "SCALA",
      imagen: "banco3.png",
      modulo: "150",
      materialBastidor: "laminado",
      respaldo: true,
      zocalo: true,
      precio: "638, 669",
    },
    {
      modelo: "SCALA",
      imagen: "banco3.png",
      modulo: "45Rincon",
      materialBastidor: "laminado",
      zocalo: true,
      precio: "416, 437",
    },
    //Modelo CUBE
    {
      modelo: "CUBE",
      imagen: "banco4.png",
      modulo: "45",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 93,
      zocalo: true,
      precio: "219, 230",
    },
    {
      modelo: "CUBE",
      imagen: "banco4.png",
      modulo: "90",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 121,
      zocalo: true,
      precio: "289, 303",
    },
    {
      modelo: "CUBE",
      imagen: "banco4.png",
      modulo: "120",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 139,
      zocalo: true,
      precio: "334, 351",
    },
    {
      modelo: "CUBE",
      imagen: "banco4.png",
      modulo: "150",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 156,
      zocalo: true,
      precio: "364, 382",
    },
    {
      modelo: "CUBE",
      imagen: "banco4.png",
      modulo: "45Rincon",
      materialBastidor: "laminado",
      respaldo: true,
      precioRespaldo: 93,
      zocalo: true,
      precio: "252, 265",
    },
    //Modelo HALL
    {
      modelo: "HALL",
      imagen: "banco5.png",
      modulo: "45",
      materialBastidor: "laminado",
      precio: "235, 247",
    },
    {
      modelo: "HALL",
      imagen: "banco5.png",
      modulo: "90",
      materialBastidor: "laminado",
      precio: "288, 302",
    },
    {
      modelo: "HALL",
      imagen: "banco5.png",
      modulo: "120",
      materialBastidor: "laminado",
      precio: "314, 330",
    },
    {
      modelo: "HALL",
      imagen: "banco5.png",
      modulo: "150",
      materialBastidor: "laminado",
      precio: "358, 376",
    },
  ]);
}
