import { db } from "./index";
import { mesas, usuarios, colores, sillas } from "./schema";

export async function insertarMesas() {
  try {
    // modificar la ruta de la imagen en el insert
    const newMesa1 = await db.insert(mesas).values({
      modelo: "LOMMA",
      imagen: "lomma.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      tendencia: true,
      precio: 250,
    });
    const newMesa2 = await db.insert(mesas).values({
      modelo: "DUBLIN",
      imagen: "m1.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "100x30",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      precio: 150,
    });
    const newMesa3 = await db.insert(mesas).values({
      modelo: "TARRAGONA",
      imagen: "ejemplo.png",
      tipoBase: "peninsula",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      nuevo: true,
      precio: 200,
    });
    const newMesa4 = await db.insert(mesas).values({
      modelo: "ROMA",
      imagen: "m2.png",
      tipoBase: "4 patas",
      materialTapa: "laminado",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "aluminio",
      colorPata: "blanco",
      nuevo: true,
      precio: 450,
    });
    const newMesa5 = await db.insert(mesas).values({
      modelo: "CADIZ",
      imagen: "m3.png",
      tipoBase: "4 patas",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
    const newMesa6 = await db.insert(mesas).values({
      modelo: "SEVILLA",
      imagen: "m4.png",
      tipoBase: "alas",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
    const newMesa7 = await db.insert(mesas).values({
      modelo: "ONTARO",
      imagen: "m5.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
    const newMesa8 = await db.insert(mesas).values({
      modelo: "DUBLIN",
      imagen: "m6.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: 350,
    });
    const newMesa9 = await db.insert(mesas).values({
      modelo: "FRANCIA",
      imagen: "m7.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: 350,
    });
    const newMesa10 = await db.insert(mesas).values({
      modelo: "TAILANDIA",
      imagen: "m8.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: 350,
    });
    const newMesa11 = await db.insert(mesas).values({
      modelo: "TOKIO",
      imagen: "m9.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
    const newMesa12 = await db.insert(mesas).values({
      modelo: "NUEVA YORK",
      imagen: "m10.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: 350,
    });
    const newMesa13 = await db.insert(mesas).values({
      modelo: "ESTAMBUL",
      imagen: "m11.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      tendencia: true,
      precio: 350,
    });
    const newMesa14 = await db.insert(mesas).values({
      modelo: "LAGOS",
      imagen: "m12.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
    const newMesa15 = await db.insert(mesas).values({
      modelo: "SEÚL",
      imagen: "m13.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      precio: 350,
    });
    const newMesa16 = await db.insert(mesas).values({
      modelo: "EL CAIRO",
      imagen: "m14.png",
      tipoBase: "pie central",
      extension: "extensible",
      tipoAmpliable: "lateral",
      auxiliar: "simple",
      materialTapa: "cristal 8mm",
      colorTapa: "blanco",
      dimensiones: "120x80",
      altura: "77, 92, 112",
      materialPata: "madera",
      colorPata: "blanco",
      nuevo: true,
      precio: 350,
    });
  } catch (error) {
    console.error("Error al insertar mesas:", error);
    return new Response("Error al insertar mesas", { status: 500 });
  }
}
